Repository mangomaneya/HotPlaceInSeoul, pull requests merged in 2025-02, with the labels that each got.

#6 chore:#5 css파일 연결 및 eslint prop-types check off처리
  eslint.config.js
  src/main.jsx
  src/style/global.css
Labels: ⚙ Setting, 🎨 Styles

#9 Feature/#2 layout
  index.html
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Nav.jsx
  src/constants/path-constant.js
  src/pages/Home.jsx
  src/router/Router.jsx
  src/style/global.css
  tailwind.config.js
Labels: ✨ Feature, 🎨 Styles

#13 Feature/#8 auth 로직 구현
  .gitignore
  package.json
  pnpm-lock.yaml
  src/lib/api/supabaseAPI.js
  src/lib/hooks/useSignUpForm.js
  src/lib/utils/signUpValidate.js
Labels: ✨ Feature, 📬 API

#15 Feature/#10 youtube modal layout
  package.json
  pnpm-lock.yaml
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/components/modal/detail-modal.jsx
  src/constants/alert-constant.js
  src/constants/store-constant.js
  src/lib/utils/openAlert.js
  src/main.jsx
  src/style/global.css
Labels: ✨ Feature, 🎨 Styles

#20 Feature/#8 회원가입 페이지
  jsconfig.json
  src/components/sign-up/InputForm.jsx
  src/components/sign-up/SignUpForm.jsx
  src/lib/hooks/useSignUp.js
  src/lib/utils/signUpValidate.js
  src/pages/SignUp.jsx
  src/router/Router.jsx
  tailwind.config.js
  vite.config.js
Labels: ✨ Feature, 🎨 Styles

#25 chore:#23 package 추가
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#24 Feature/#19 zustand 설정 작업 (회원정보와 로그인 여부)
  src/store/zustand/authStore.js
Labels: ✨ Feature, ⚙ Setting

#27 Feature/#21 로그인 페이지
  jsconfig.json
  src/components/common/InputForm.jsx
  src/components/login/LoginForm.jsx
  src/components/sign-up/SignUpForm.jsx
  src/lib/api/api.js
  src/lib/hooks/useLogin.js
  src/lib/hooks/useSignUp.js
  src/pages/Login.jsx
  src/router/Router.jsx
  src/store/zustand/authStore.js
  tailwind.config.js
  vite.config.js
Labels: ✨ Feature, 🎨 Styles
