Repository mangomaneya/HotPlaceInSeoul, pull requests merged in 2025-03, with the labels that each got.

#38 Feature/#29 youtube api
  package.json
  pnpm-lock.yaml
  src/components/common/Error.jsx
  src/components/common/Loading.jsx
  src/components/modal/detail-modal.jsx
  src/components/modal/youtube-modal.jsx
  src/lib/queries/useYoutubeQuery.js
  src/lib/utils/formatDate.js
  src/style/global.css
Labels: ✨ Feature, 🎨 Styles, 📬 API

#34 Feature/#31 header nav refactor
  src/components/layout/Header.jsx
  src/components/layout/Nav.jsx
  src/constants/path-constant.js
  src/lib/hooks/useLogin.js
  src/lib/hooks/useLogout.js
  src/lib/hooks/useSignUp.js
  src/store/zustand/authStore.js
Labels: 🔨 Refactor, ✨ Feature

#39 Feature/#37 protected router
  src/App.jsx
  src/constants/path-constant.js
  src/lib/hooks/useLogout.js
  src/pages/NotFoundedPage.jsx
  src/router/ProtectedRouter.jsx
  src/router/Router.jsx
  src/router/Routes.jsx
Labels: 🔨 Refactor, ✨ Feature

#35 Feature#22 hotplace list DB 연결 및 모달창 띄우기
  src/components/HotplaceList/HotplaceList.jsx
  src/lib/queries/GetHotplaces.js
  src/pages/BookMark.jsx
  src/pages/BookMark/BookMark.jsx
  src/pages/BookMark/ListData.js
  src/router/Router.jsx
  src/style/global.css
Labels: 🔨 Refactor, 📬 API

#42 Chore/#41-new-font-pretendard
  index.html
  src/style/global.css
  tailwind.config.js
Labels: ✨ Feature

#48 Refactor/#32 회원가입 페이지 리팩토링
  src/components/sign-up/SignUpForm.jsx
  src/pages/SignUp.jsx
Labels: 🔨 Refactor, 🎨 Styles

#55 Hotfix/#54 배포오류 수정
  src/components/map-api/KakaoMap.jsx
Labels: 🐞 BugFix

#50 refactor: Router 컴포넌트를 Routes로 변경하고 북마크 및 404 페이지 추가
  src/App.jsx
  src/components/layout/Nav.jsx
  src/router/Router.jsx
  src/router/Routes.jsx
Labels: 🔨 Refactor, ✨ Feature

#49 Refactor#36 bookmark page
  src/components/HotplaceList/HotplaceList.jsx
  src/lib/queries/GetBookmarks.js
  src/pages/BookMark.jsx
  src/pages/BookMark/BookMark.jsx
  src/pages/BookMark/ListData.js
Labels: 🔨 Refactor, 📬 API

#51 Feature/#40 bookmark api
  src/components/common/Error.jsx
  src/components/modal/detail-modal.jsx
  src/constants/path-constant.js
  src/constants/query-keys.js
  src/constants/store-constant.js
  src/lib/api/bookmarkAPI.js
  src/lib/mutation/useBookmarkMutation.js
  src/lib/queries/useBookmarkQuery.js
  src/lib/queries/useYoutubeQuery.js
Labels: 🔨 Refactor, 📬 API

#61 Feature/#57 not found page
  src/pages/NotFoundedPage.jsx
Labels: ✨ Feature, 🎨 Styles

#68 Refactor/#65 detail modal youtube modal 연결
  README.md
  src/App.jsx
  src/components/HotplaceList/HotplaceList.jsx
  src/components/common/Error.jsx
  src/components/layout/Nav.jsx
  src/components/map-api/KakaoMap.jsx
  src/components/map-api/MapController.jsx
  src/components/map-api/MarkerInfo.jsx
  src/components/modal/detail-modal.jsx
  src/components/modal/youtube-modal.jsx
  src/constants/path-constant.js
  src/constants/query-keys.js
  src/constants/store-constant.js
  src/lib/api/bookmarkAPI.js
  src/lib/mutation/useBookmarkMutation.js
  src/lib/queries/GetBookmarks.js
  src/lib/queries/GetHotplaces.js
  src/lib/queries/useBookmarkQuery.js
  src/lib/queries/useYoutubeQuery.js
  src/pages/BookMark.jsx
  src/pages/BookMark/BookMark.jsx
  src/pages/BookMark/ListData.js
  src/pages/Home.jsx
  src/pages/NotFoundedPage.jsx
  src/router/Router.jsx
  src/router/Routes.jsx
  src/store/zustand/useAreaStore.js
  src/style/global.css
Labels: 🔨 Refactor, ✨ Feature

#64 Feature/#46 토큰만료 이슈와, 로그아웃 에러 발생 시 메시지 수정
  src/lib/hooks/useLogout.js
  src/router/Routes.jsx
Labels: 🔨 Refactor, ✨ Feature

#72 Docs/#66 read me 작성
  README.md
Labels: 📃 Docs

#69 Refactor#58 hotplace list 지역별 적용
  src/components/HotplaceList/HotplaceList.jsx
  src/components/layout/Header.jsx
  src/constants/query-keys.js
  src/lib/queries/GetBookmarks.js
  src/lib/queries/GetHotplaces.js
  src/pages/BookMark.jsx
  src/store/zustand/useAreaStore.js
Labels: 🔨 Refactor, ✨ Feature

#73 Refactor/#65 detail modal youtube modal 연결
  src/components/HotplaceList/HotplaceList.jsx
  src/components/map-api/KakaoMap.jsx
Labels: 🔨 Refactor, ✨ Feature

#77 Refactor/#76 기타작업
  README.md
  index.html
  jsconfig.json
  public/favicon.svg
  src/components/HotplaceList/HotplaceList.jsx
  src/components/common/Error.jsx
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Nav.jsx
  src/components/login/LoginForm.jsx
  src/components/map-api/KakaoMap.jsx
  src/components/map-api/MapController.jsx
  src/components/modal/detail-modal.jsx
  src/components/modal/youtube-modal.jsx
  src/components/sign-up/SignUpForm.jsx
  src/lib/api/bookmarkAPI.js
  src/lib/hooks/useLogin.js
  src/lib/hooks/useLogout.js
  src/lib/hooks/useSignUp.js
  src/lib/mutation/useBookmarkMutation.js
  src/lib/queries/GetBookmarks.js
  src/lib/queries/GetHotplaces.js
  src/lib/queries/useBookmarkQuery.js
  src/lib/queries/useYoutubeQuery.js
  src/lib/utils/openAlert.js
  src/main.jsx
  src/pages/BookMark.jsx
  src/pages/Home.jsx
  src/pages/NotFoundedPage.jsx
  src/pages/SignUp.jsx
  src/router/ProtectedRouter.jsx
  src/router/Routes.jsx
  vite.config.js
Labels: 🌏 Deploy, 📃 Docs, 🔨 Refactor

#83 chore:#82 모달 absolute -> fixed로 수정
  src/style/global.css
Labels: 🐞 BugFix
